import type { Report } from './types';
export const example: Report = {
    brief: { company: 'PostHog', website: 'https://posthog.com', audience: 'Developers evaluating product analytics for a web application', objective: 'Help developers reach a useful product evaluation, with an optional technical walkthrough.', constraints: 'Independent portfolio study. Public information only. Demo growth is a hypothesis, not a confirmed company priority.' },
    summary: 'Make the first useful insight easier to reach.', generatedAt: '2026-09-10T12:00:00Z', mode: 'example',
    warnings: ['Curated example from an initial public research pass. Not a live run.', 'Complaint-led convenience sample; themes do not measure prevalence.'],
    evidence: [
        { id: 'E1', title: 'New user reports navigation difficulty', url: 'https://www.reddit.com/r/posthog/comments/1qg7n2n/the_ux_is_just_terrible_new_user_rant/', summary: 'A poster reports spending three hours navigating without understanding where things are. Replies describe trouble with particular tasks.', kind: 'complaint', date: null, limitation: 'Self-reported experience. Publication date and current reproducibility need verification.' },
        { id: 'E2', title: 'Prospect leaves before creating an account', url: 'https://www.reddit.com/r/posthog/comments/1t7c4ws/but_is_it_any_good/', summary: 'A prospective buyer says the website design discouraged them from trying the product.', kind: 'complaint', date: '2026-05-08', limitation: 'One self-reported evaluation; identity and conversion impact are unverified.' },
        { id: 'E3', title: 'Broad demo feels overwhelming', url: 'https://news.ycombinator.com/item?id=45217269', summary: 'A commenter describes navigation and pricing confusion and says the demo made the product look complex.', kind: 'complaint', date: null, limitation: 'Historical website discussion. Recheck the current experience before acting.' },
        { id: 'E4', title: 'Positive setup and product feedback', url: 'https://www.reddit.com/r/posthog/comments/1t7c4ws/but_is_it_any_good/', summary: 'Other participants praise the data, transparency, and AI setup wizard. Experience varies across users.', kind: 'positive', date: '2026-05-08', limitation: 'Same discussion as E2; not an independent source.' },
        { id: 'E5', title: 'Self-service is an existing path', url: 'https://posthog.com', summary: 'The public website offers free signup, public pricing, and a path that does not require a sales call.', kind: 'context', date: null, limitation: 'Company-provided positioning; not independent evidence of activation performance.' }
    ],
    opportunities: [
        { id: 'O1', title: 'One problem. One useful walkthrough.', hypothesis: 'A focused signup-drop-off walkthrough may help overwhelmed evaluators understand the workflow.', evidenceIds: ['E1', 'E3'], counterEvidenceIds: ['E4'], stage: 'Evaluate', effort: 'Low', action: 'Create a short technical walkthrough: capture signup events, build a funnel, investigate a drop-off, and choose the next question.', metric: 'Share of test participants who complete the target investigation without help.', validation: 'First test the existing journey with five developers. Compare task completion and stumbling points with the prototype; treat this as qualitative learning.', owner: 'Developer marketing' },
        { id: 'O2', title: 'Give evaluators a clear starting point', hypothesis: 'A use-case page may reduce uncertainty for developers who find the broad website difficult to navigate.', evidenceIds: ['E2', 'E3'], counterEvidenceIds: ['E4', 'E5'], stage: 'Discover', effort: 'Medium', action: 'Prototype a product-analytics page for web developers with implementation prerequisites, one example, and self-service and assisted next steps.', metric: 'Qualified evaluation starts per relevant page visitor; track downstream activation.', validation: 'Check whether an equivalent page already exists. Establish baseline and traffic needs before an A/B test.', owner: 'Product marketing' },
        { id: 'O3', title: 'Offer help at the point of friction', hypothesis: 'An optional implementation clinic may help evaluators with a concrete setup question progress.', evidenceIds: ['E1', 'E5'], counterEvidenceIds: ['E4'], stage: 'Activate', effort: 'Medium', action: 'Prototype an optional technical-session invitation after the tutorial, asking what the developer is trying to accomplish.', metric: 'Attended qualified sessions and subsequent target-task completion; monitor self-service completion.', validation: 'Validate demand through interviews. No evidence yet that increasing sales demos is a PostHog goal.', owner: 'Developer relations' }
    ], unknowns: ['How common are these difficulties among target developers?', 'Which complaints still apply to the current product?', 'What content or walkthroughs already solve these tasks?', 'What are current evaluation, activation, and assisted-conversion baselines?']
};
