import type { Report } from './types';

export const example: Report = {
  brief: {
    company: 'PostHog',
    website: 'https://posthog.com',
    audience: 'AI-oriented software teams, entering through engineers and technical founders',
    objective: 'Test how PostHog can turn its self-driving product positioning into measurable multi-product activation and selective technical assistance.',
    constraints: 'Independent portfolio thesis using public information. No access to PostHog CRM, product analytics, budgets, conversion rates, or internal targets.',
    industry: 'Developer tools and product analytics',
    businessModel: 'B2B SaaS with usage-based expansion',
    gtmMotion: 'Product-led growth with selective sales assistance',
    geography: 'Global',
    companyStage: 'Scale-up',
  },
  summary: 'Prove the self-driving product promise in public, then measure whether the proof creates multi-product activation.',
  generatedAt: '2026-09-14T12:00:00Z',
  mode: 'example',
  warnings: [
    'Portfolio thesis built from public information; it is not an internal PostHog strategy.',
    'Public complaints are a convenience sample and do not measure prevalence.',
    'The reported ARR figure is an external estimate, not a PostHog disclosure.',
    'Budgets are illustrative proposed test caps, not approved spend.',
  ],
  evidence: [
    { id: 'E1', title: 'New user reports navigation difficulty', url: 'https://www.reddit.com/r/posthog/comments/1qg7n2n/the_ux_is_just_terrible_new_user_rant/', summary: 'A poster reports spending hours navigating without understanding where things are. Replies describe difficulty completing particular tasks.', kind: 'complaint', date: null, limitation: 'Self-reported experience. Date, identity, prevalence, and current reproducibility need verification.' },
    { id: 'E2', title: 'Prospect says the website discouraged evaluation', url: 'https://www.reddit.com/r/posthog/comments/1t7c4ws/but_is_it_any_good/', summary: 'A prospective buyer says the website presentation discouraged them from creating an account.', kind: 'complaint', date: '2026-05-08', limitation: 'One self-reported evaluation; conversion impact is unknown.' },
    { id: 'E3', title: 'Broad demo described as overwhelming', url: 'https://news.ycombinator.com/item?id=45217269', summary: 'A commenter describes navigation and pricing confusion and says the broad demo made the product look complex.', kind: 'complaint', date: null, limitation: 'Historical public discussion. Recheck the current experience before acting.' },
    { id: 'E4', title: 'Other evaluators report a positive setup experience', url: 'https://www.reddit.com/r/posthog/comments/1t7c4ws/but_is_it_any_good/', summary: 'Other participants praise PostHog’s data, transparency, and setup wizard.', kind: 'positive', date: '2026-05-08', limitation: 'Same discussion as E2 and not an independent sample.' },
    { id: 'E5', title: 'PostHog is designed for self-service adoption', url: 'https://posthog.com', summary: 'PostHog offers free signup, public usage-based pricing, and states that users do not need a sales call to begin.', kind: 'context', date: null, limitation: 'Company-provided positioning, not evidence of activation performance.' },
    { id: 'E6', title: 'Current ICP is AI-oriented software teams', url: 'https://posthog.com/handbook/who-we-build-for', summary: 'PostHog says it builds for ambitious AI-oriented software teams with 1 to 500 potential PostHog users, entering through engineers and technical founders.', kind: 'context', date: null, limitation: 'Current company-defined ICP; segment-level activation and retention data are private.' },
    { id: 'E7', title: 'Strategy is product context plus automated iteration', url: 'https://posthog.com/handbook/why-does-posthog-exist', summary: 'PostHog’s stated strategy is to become the source of truth for product context, provide engineers a broad toolset, get adopted early, and automate shipping, observing, and iterating.', kind: 'context', date: null, limitation: 'Company strategy describes intent, not proven market understanding.' },
    { id: 'E8', title: 'Activation is defined by product-specific behaviors', url: 'https://newsletter.posthog.com/p/wtf-is-activation-and-why-should', summary: 'PostHog has published behavioral activation definitions for experimentation, feature flags, product analytics, surveys, and session replay, with 14- or 30-day windows.', kind: 'context', date: null, limitation: 'Published definitions do not reveal current conversion rates or targets.' },
    { id: 'E9', title: 'Marketing emphasizes brand, content, website, and launches', url: 'https://newsletter.posthog.com/p/40-things-weve-learned-about-marketing', summary: 'PostHog says it markets mainly to developers and prioritizes remarkable products, brand, content, its website, and launches over generic marketing channels.', kind: 'context', date: '2025-07-21', limitation: 'Published philosophy does not quantify current channel performance.' },
    { id: 'E10', title: 'Revenue motion is primarily inbound and product-led', url: 'https://posthog.com/handbook/growth/sales/overview', summary: 'PostHog says most paying customers arrive without sales contact. Its teams focus on inbound, warm product-led assistance, cross-sell, onboarding, and customers paying or capable of paying at least $20,000 per year.', kind: 'context', date: null, limitation: 'The threshold is a service focus, not average contract value.' },
    { id: 'E11', title: 'Revenue ambition is materially above the user’s estimate', url: 'https://stripe.com/customers/posthog', summary: 'Stripe describes PostHog as on pace for $100 million ARR and reports that 41% of revenue flows through in-product checkout.', kind: 'positive', date: null, limitation: 'Stripe does not disclose current ARR on this page; “on pace” is directional.' },
    { id: 'E12', title: 'External source estimates roughly $58M ARR', url: 'https://sacra.com/c/posthog/', summary: 'Sacra estimates PostHog reached approximately $57.5 million ARR in February 2026.', kind: 'context', date: null, limitation: 'Third-party estimate. Do not present as an audited or company-reported figure.' },
  ],
  marketContext: {
    thesis: 'PostHog’s platform story may be outrunning developer comprehension.',
    facts: [
      { label: 'Business model', value: 'Product-led, usage-based SaaS with generous free tiers and paid expansion across multiple products.', status: 'Public fact', evidenceIds: ['E5', 'E10'] },
      { label: 'Primary ICP', value: 'Ambitious AI-oriented software teams with 1–500 potential PostHog users.', status: 'Public fact', evidenceIds: ['E6'] },
      { label: 'Entry persona', value: 'Engineers and technical founders; adoption can spread to product, support, and marketing builders.', status: 'Public fact', evidenceIds: ['E6'] },
      { label: 'Positioning', value: 'A source of product context that helps teams automate the ship → observe → iterate cycle.', status: 'Public fact', evidenceIds: ['E7'] },
      { label: 'Revenue direction', value: 'Stripe describes the company as on pace for $100M ARR; Sacra estimates about $57.5M in February 2026.', status: 'Inference', evidenceIds: ['E11', 'E12'] },
      { label: 'Average contract value', value: 'Unknown. The sales handbook prioritizes accounts at $20k+ annual potential and defines $250k+ as one signal of a large deal.', status: 'Unknown', evidenceIds: ['E10'] },
      { label: 'Commercial objective', value: 'Increase multi-product activation and expansion while preserving fast self-service adoption.', status: 'Inference', evidenceIds: ['E8', 'E10'] },
      { label: 'Competitive frame', value: 'A consolidated developer-first alternative to separate analytics, replay, flagging, experimentation, warehouse, and observability tools.', status: 'Inference', evidenceIds: ['E7'] },
    ],
    funnel: [
      { name: 'Acquire', signal: 'Brand, technical content, website, launches, word of mouth', state: 'Known' },
      { name: 'Evaluate', signal: 'Free signup and first useful product task', state: 'Hypothesis' },
      { name: 'Activate', signal: 'Published product-specific 14- and 30-day behaviors', state: 'Known' },
      { name: 'Expand', signal: 'Cross-activation into multiple products and in-product checkout', state: 'Known' },
      { name: 'Retain', signal: 'Segment and product retention rates are unavailable', state: 'Missing data' },
    ],
  },
  benchmarkProfile: {
    category: 'Developer tools and product analytics',
    businessModel: 'B2B SaaS with usage-based expansion',
    gtmMotion: 'Product-led growth with selective sales assistance',
    companyStage: 'Scale-up',
    geography: 'Global',
    peers: [],
    metrics: [
      { name: 'Product-specific activation', definition: 'Completion of a meaningful behavior within a product-specific 14- or 30-day window.', observedRange: null, unit: 'percentage of qualified new accounts', evidenceIds: ['E8'], freshness: 'Definition is public; performance date is unavailable.', limitation: 'PostHog publishes definitions but no comparable cohort range. Internal product analytics and matched peer data are required.' },
      { name: 'Self-serve revenue share', definition: 'Revenue completed through an in-product checkout without a sales-led close.', observedRange: null, unit: 'percentage of revenue', evidenceIds: ['E10', 'E11'], freshness: 'Current public pages; reporting period is not disclosed.', limitation: 'A company-specific directional signal, not an industry benchmark or a complete measure of sales assistance.' },
    ],
    conventions: ['Free self-serve entry', 'Technical education and launch content', 'Feature-led comparison pages', 'Product-qualified sales assistance'],
    whitespace: ['Make the full ship → observe → iterate loop inspectable instead of describing it', 'Turn acknowledged product limitations into a participatory developer challenge', 'Measure whether unusual brand attention creates qualified activation rather than impressions'],
  },
  assumptions: [
    { id: 'A1', title: 'Positioning comprehension', statement: 'The shift from product analytics to a self-driving product platform creates evaluation uncertainty for some qualified developers.', confidence: 'Low', impact: 'High', evidenceIds: ['E1', 'E2', 'E3', 'E7'], whyItMatters: 'If qualified users already understand the expanded story, a new proof experience will not solve a meaningful bottleneck.', validation: 'Measure comprehension and target-task selection with 8–12 ICP evaluators before changing acquisition.' },
    { id: 'A2', title: 'Activation over demo volume', statement: 'Meaningful self-service activation and selective technical assistance are more valuable than maximizing booked demos.', confidence: 'High', impact: 'High', evidenceIds: ['E5', 'E8', 'E10'], whyItMatters: 'Optimizing for demo volume could conflict with PostHog’s product-led model and attract lower-intent conversations.', validation: 'Compare activated, assisted, and unassisted ICP cohorts using account quality, multi-product activation, expansion, and retention.' },
    { id: 'A3', title: 'Public proof changes behavior', statement: 'A transparent, participatory proof of the self-driving loop will create more qualified activation than a conventional feature walkthrough.', confidence: 'Low', impact: 'High', evidenceIds: ['E7', 'E9'], whyItMatters: 'This is the creative mechanism behind the recommended bet; the evidence supports brand fit, not performance.', validation: 'Run one facilitated prototype and one unmoderated version before production or distribution spend.' },
    { id: 'A4', title: 'Revenue baseline', statement: 'Approximately $57.5M ARR is a usable external planning reference, while the internal baseline remains unknown.', confidence: 'Low', impact: 'Medium', evidenceIds: ['E11', 'E12'], whyItMatters: 'A false baseline would make revenue targets and required pipeline math misleading.', validation: 'Replace with an authorized internal ARR and expansion target; otherwise omit revenue forecasts.' },
    { id: 'A5', title: 'Current funnel performance', statement: 'The highest-leverage loss occurs between evaluation and multi-product activation.', confidence: 'Low', impact: 'High', evidenceIds: ['E1', 'E3', 'E8'], whyItMatters: 'The recommended experiments should move to a different stage if acquisition, retention, or paid conversion is the actual constraint.', validation: 'Pull signup, first-team-event, saved-insight, replay-analysis, flag, experiment, checkout, and retention cohorts from PostHog and Stripe.' },
  ],
  operatingPlan: {
    decision: {
      problem: 'Test whether a public ship → observe → iterate proof makes the expanded platform easier to understand and activate.',
      evidenceIds: ['E1', 'E3', 'E7', 'E8'],
      intervention: 'Prototype a public proof where PostHog observes a real product problem, proposes a fix, and measures the result.',
      desiredOutcome: 'More qualified evaluators complete meaningful activation events across more than one PostHog product.',
      horizon: '21-day proof sprint after an 8–12 person comprehension baseline.',
      successMetric: 'Primary: multi-product activation within 30 days. Diagnostic: proof completion and qualified assistance requests.',
      baseline: null,
      target: null,
      assumptions: ['Evaluation-to-activation is the current constraint.', 'A public proof is consistent with PostHog’s brand.', 'Internal cohort data will replace illustrative planning inputs.'],
    },
    channels: [
      { channel: 'Paid media', decision: 'Hold', rationale: 'Amplify proven demand later; do not use paid distribution to manufacture interest.', evidenceIds: ['E9'], dataNeeded: 'Incremental qualified activation and approved audience/privacy rules.' },
      { channel: 'Organic & SEO', decision: 'Investigate', rationale: 'Hold distribution design until the live proof establishes a useful technical artifact.', evidenceIds: ['E9'], dataNeeded: 'Qualified search demand, task starts, activation, and assisted conversions.' },
      { channel: 'Email & lifecycle', decision: 'Investigate', rationale: 'Offer consented, behavior-triggered assistance when an evaluator stalls on an activation event.', evidenceIds: ['E8', 'E10'], dataNeeded: 'Current automations, trigger precision, replies, activation, and unsubscribe guardrails.' },
      { channel: 'Inbound & website', decision: 'Test', rationale: 'Make the self-driving promise inspectable through one live product loop.', evidenceIds: ['E5', 'E7'], dataNeeded: 'Path selection, first useful task, proof completion, and downstream activation.' },
      { channel: 'Community & developer relations', decision: 'Investigate', rationale: 'Recruit the first validation cohort; delay a public challenge until the core proof survives it.', evidenceIds: ['E6', 'E9'], dataNeeded: 'Participant fit, completion, feedback, referrals, and moderation capacity.' },
      { channel: 'Partnerships & events', decision: 'Hold', rationale: 'Events are less scalable; consider a physical expression only after the digital proof works.', evidenceIds: ['E10'], dataNeeded: 'Digital proof performance, partner quality, attributable activation, and production cost.' },
      { channel: 'Sales & CRM', decision: 'Investigate', rationale: 'Offer technical assistance to high-potential accounts based on product behavior.', evidenceIds: ['E10'], dataNeeded: 'Account potential, activation triggers, routing, assistance acceptance, and expansion.' },
    ],
  },
  opportunities: [
    { id: 'O1', priority: 'Now', territory: 'Product as proof', behavior: 'Turn positioning comprehension into a completed product task.', title: 'The self-driving product trial', hypothesis: 'An inspectable ship → observe → iterate loop will help qualified developers understand the platform and activate across multiple products.', evidenceIds: ['E6', 'E7', 'E8', 'E9'], counterEvidenceIds: ['E4'], stage: 'Activate', effort: 'Medium', action: 'Instrument a small open-source application, introduce one consented usability defect, let PostHog identify the signal and draft a fix, then publish the human-reviewed change and measured outcome.', metric: 'Proof completion and multi-product activation within 30 days, segmented by ICP fit.', validation: 'Run the story with 8–12 target developers. Establish existing comprehension and activation before comparing the prototype.', owner: 'Website + growth engineering', design: { channel: 'Inbound & website', ambition: 'Core', mechanism: 'The product demonstrates its own value through a complete, inspectable improvement loop.', differentBecause: 'The experience exposes data, uncertainty, proposed code, human approval, and the result instead of presenting a feature tour.', smallestTest: 'One synthetic app, one problem, one facilitated session, and a static trace before any public build.', budgetCap: 1000, durationDays: 21, stopRule: 'Stop if target developers cannot explain the platform more clearly after the proof or if the loop requires misleading automation claims.', primaryMetric: 'Multi-product activation among qualified proof participants', guardrail: 'No production customer data, hidden code changes, or unsupported causal claims.' } },
    { id: 'O2', priority: 'Next', territory: 'Community competition', behavior: 'Create participation, technical status, and adversarial product learning.', title: 'Break the hedgehog', hypothesis: 'An adversarial developer challenge can generate more useful product learning and qualified activation than a polished webinar.', evidenceIds: ['E6', 'E9'], counterEvidenceIds: ['E4'], stage: 'Discover', effort: 'Medium', action: 'Give invited developers a sandbox and ask them to create edge cases the self-driving workflow misdiagnoses. Publish the failures, fixes, and winner’s technical write-up.', metric: 'Qualified participants, valid failure cases, activated products, and participant-authored referrals.', validation: 'Run a five-person closed red-team session before making the challenge public.', owner: 'Developer relations + product', design: { channel: 'Community & developer relations', ambition: 'Bold', mechanism: 'Developers earn status by finding where automation fails, while PostHog earns trust by exposing and fixing those failures.', differentBecause: 'The company markets limitations and learning rather than staging a flawless demo.', smallestTest: 'Five developers, a private sandbox, one two-hour session, and no prize beyond public credit.', budgetCap: 2500, durationDays: 14, stopRule: 'Stop if the challenge attracts exploit behavior without useful learning or participants do not reach an activation event.', primaryMetric: 'Valid product-learning cases per qualified participant', guardrail: 'Sandbox only, responsible disclosure rules, participant consent, and no production access.' } },
    { id: 'O3', priority: 'Later', territory: 'Radical transparency', behavior: 'Turn company operations into a recurring reason to follow the product.', title: 'The brutally honest changelog', hypothesis: 'A live ledger of failed experiments and rejected AI suggestions can make the self-driving claim more credible and memorable.', evidenceIds: ['E7', 'E9'], counterEvidenceIds: ['E4'], stage: 'Evaluate', effort: 'Medium', action: 'Publish a weekly machine-readable ledger showing what the agent proposed, what humans rejected, what shipped, what was reverted, and what changed in the metric.', metric: 'Qualified return visits, proof-to-product activation, technical citations, and assisted account activity.', validation: 'Publish one manually curated edition and interview readers about credibility and usefulness.', owner: 'Content + engineering', design: { channel: 'Organic & SEO', ambition: 'Bold', mechanism: 'Rejected and failed work becomes useful product evidence rather than being hidden.', differentBecause: 'Most launch content celebrates successes; this artifact makes judgment and reversals the product story.', smallestTest: 'One edition covering three real or clearly synthetic decisions with evidence and code links.', budgetCap: 750, durationDays: 14, stopRule: 'Stop if readers interpret the ledger as production instability or entries cannot be verified.', primaryMetric: 'Qualified proof-to-product activation', guardrail: 'No confidential data, employee blame, customer exposure, or fabricated failures.' } },
    { id: 'O4', priority: 'Later', territory: 'Physical absurdity', behavior: 'Create a tangible, shareable representation of safe product iteration.', title: 'The feature-flagged canary', hypothesis: 'A strange physical artifact connected to a sandbox can earn attention while teaching how safe releases and product signals work together.', evidenceIds: ['E7', 'E9', 'E10'], counterEvidenceIds: ['E4'], stage: 'Discover', effort: 'High', action: 'Prototype an animatronic canary whose behavior changes through a PostHog feature flag while a public dashboard shows exposure, errors, replays, and rollback.', metric: 'Completed safe-release tasks and subsequent product activation, separated from photos and scans.', validation: 'Test a browser-based simulation and paper prop with one developer meetup before building hardware.', owner: 'Brand + developer relations', design: { channel: 'Partnerships & events', ambition: 'Wildcard', mechanism: 'A deployment metaphor becomes a controllable physical object backed by real feature-flag and telemetry behavior.', differentBecause: 'The weird object is functional: participants ship, observe, and roll back instead of receiving branded merchandise.', smallestTest: 'A browser animation, cardboard canary, ten invited participants, and no hardware fabrication.', budgetCap: 1500, durationDays: 21, stopRule: 'Stop if people remember the prop but cannot explain the safe-release workflow or attributable activation is absent.', primaryMetric: 'Completed safe-release tasks per qualified participant', guardrail: 'No production control, accessible digital alternative, hard spend cap, and reusable materials.' } },
  ],
  unknowns: [
    'Which segment currently activates and retains best across multiple products?',
    'Where does the highest-value ICP cohort drop between signup and the first two activation events?',
    'How well do evaluators understand the new self-driving product positioning?',
    'What are current assisted and unassisted expansion rates?',
    'Which existing content, demos, or product experiences already address this thesis?',
  ],
};
