import {posthogEconomics} from './posthog-economics.ts';
import type { Report } from './types';

export const example: Report = {
  economics: posthogEconomics,
  brief: {
    company: 'PostHog',
    website: 'https://posthog.com',
    audience: 'For engineers and technical founders building with AI',
    objective: 'Test how PostHog can turn its self-driving product positioning into measurable multi-product activation and selective technical assistance.',
    constraints: 'Independent portfolio thesis using public information. No access to PostHog CRM, product analytics, budgets, conversion rates, or internal targets.',
    industry: 'Developer tools and product analytics',
    businessModel: 'B2B SaaS with usage-based expansion',
    gtmMotion: 'Product-led growth with selective sales assistance',
    geography: 'Global',
    companyStage: 'Scale-up',
  },
  summary: 'Let developers watch the product solve a problem. Then check whether they actually use it.',
  generatedAt: '2026-09-14T12:00:00Z',
  mode: 'example',
  warnings: [
    'Portfolio thesis built from public information; it is not an internal PostHog strategy.',
    'Public complaints are a convenience sample and do not measure prevalence.',
    'The reported ARR figure is an external estimate, not a PostHog disclosure.',
    'Budgets are illustrative proposed test caps, not approved spend.',
  ],
  evidence: [
    { id: 'E1', title: 'New user reports navigation difficulty', url: 'https://www.reddit.com/r/posthog/comments/1qg7n2n/the_ux_is_just_terrible_new_user_rant/', summary: 'A poster reports spending hours navigating without understanding where things are. Replies describe difficulty completing particular tasks.', kind: 'complaint', date: null, limitation: 'Self-reported experience. Date, identity, prevalence, and current reproducibility need verification.' },
    { id: 'E2', title: 'Prospect says the website discouraged evaluation', url: 'https://www.reddit.com/r/posthog/comments/1t7c4ws/but_is_it_any_good/', summary: 'A prospective buyer says the website presentation discouraged them from creating an account.', kind: 'complaint', date: '2026-05-08', limitation: 'One self-reported evaluation; conversion impact is unknown.' },
    { id: 'E3', title: 'Broad demo described as overwhelming', url: 'https://news.ycombinator.com/item?id=45217269', summary: 'A commenter describes navigation and pricing confusion and says the broad demo made the product look complex.', kind: 'complaint', date: null, limitation: 'Historical public discussion. Recheck the current experience before acting.' },
    { id: 'E4', title: 'Other evaluators report a positive setup experience', url: 'https://www.reddit.com/r/posthog/comments/1t7c4ws/but_is_it_any_good/', summary: 'Other participants praise PostHog’s data, transparency, and setup wizard.', kind: 'positive', date: '2026-05-08', limitation: 'Same discussion as E2 and not an independent sample.' },
    { id: 'E5', title: 'PostHog is designed for self-service adoption', url: 'https://posthog.com', summary: 'PostHog offers free signup, public usage-based pricing, and states that users do not need a sales call to begin.', kind: 'context', date: null, limitation: 'Company-provided positioning, not evidence of activation performance.' },
    { id: 'E6', title: 'Current ICP is AI-oriented software teams', url: 'https://posthog.com/handbook/who-we-build-for', summary: 'PostHog says it builds for ambitious AI-oriented software teams with 1 to 500 potential PostHog users, entering through engineers and technical founders.', kind: 'context', date: null, limitation: 'Current company-defined ICP; segment-level activation and retention data are private.' },
    { id: 'E7', title: 'Strategy is product context plus automated iteration', url: 'https://posthog.com/handbook/why-does-posthog-exist', summary: 'PostHog’s stated strategy is to become the source of truth for product context, provide engineers a broad toolset, get adopted early, and automate shipping, observing, and iterating.', kind: 'context', date: null, limitation: 'Company strategy describes intent, not proven market understanding.' },
    { id: 'E8', title: 'Activation is defined by product-specific behaviors', url: 'https://newsletter.posthog.com/p/wtf-is-activation-and-why-should', summary: 'PostHog has published behavioral activation definitions for experimentation, feature flags, product analytics, surveys, and session replay, with 14- or 30-day windows.', kind: 'context', date: null, limitation: 'Published definitions do not reveal current conversion rates or targets.' },
    { id: 'E9', title: 'Marketing emphasizes brand, content, website, and launches', url: 'https://newsletter.posthog.com/p/40-things-weve-learned-about-marketing', summary: 'PostHog says it markets mainly to developers and prioritizes remarkable products, brand, content, its website, and launches over generic marketing channels.', kind: 'context', date: '2025-07-21', limitation: 'Published philosophy does not quantify current channel performance.' },
    { id: 'E10', title: 'Revenue motion is primarily inbound and product-led', url: 'https://posthog.com/handbook/growth/sales/overview', summary: 'PostHog says most paying customers arrive without sales contact. Its teams focus on inbound, warm product-led assistance, cross-sell, onboarding, and customers paying or capable of paying at least $20,000 per year.', kind: 'context', date: null, limitation: 'The threshold is a service focus, not average contract value.' },
    { id: 'E11', title: 'Revenue ambition is materially above the user’s estimate', url: 'https://stripe.com/customers/posthog', summary: 'Stripe describes PostHog as on pace for $100 million ARR and reports that 41% of revenue flows through in-product checkout.', kind: 'positive', date: null, limitation: 'Stripe does not disclose current ARR on this page; “on pace” is directional.' },
    { id: 'E12', title: 'External source estimates roughly $58M ARR', url: 'https://sacra.com/c/posthog/', summary: 'Sacra estimates PostHog reached approximately $57.5 million ARR in February 2026.', kind: 'context', date: null, limitation: 'Third-party estimate. Do not present as an audited or company-reported figure.' },
  ],
  marketContext: {
    thesis: 'Can developers see how the pieces fit together? We think a hands-on test could help.',
    facts: [
      { label: 'Business model', value: 'Product-led, usage-based SaaS with generous free tiers and paid expansion across multiple products.', status: 'Public fact', evidenceIds: ['E5', 'E10'] },
      { label: 'Primary ICP', value: 'Ambitious AI-oriented software teams with 1–500 potential PostHog users.', status: 'Public fact', evidenceIds: ['E6'] },
      { label: 'Entry persona', value: 'Engineers and technical founders; adoption can spread to product, support, and marketing builders.', status: 'Public fact', evidenceIds: ['E6'] },
      { label: 'Positioning', value: 'A source of product context that helps teams automate the ship → observe → iterate cycle.', status: 'Public fact', evidenceIds: ['E7'] },
      { label: 'Revenue direction', value: 'Stripe describes the company as on pace for $100M ARR; Sacra estimates about $57.5M in February 2026.', status: 'Inference', evidenceIds: ['E11', 'E12'] },
      { label: 'Average contract value', value: 'Unknown. The sales handbook prioritizes accounts at $20k+ annual potential and defines $250k+ as one signal of a large deal.', status: 'Unknown', evidenceIds: ['E10'] },
      { label: 'Commercial objective', value: 'Increase multi-product activation and expansion while preserving fast self-service adoption.', status: 'Inference', evidenceIds: ['E8', 'E10'] },
      { label: 'Competitive frame', value: 'A consolidated developer-first alternative to separate analytics, replay, flagging, experimentation, warehouse, and observability tools.', status: 'Inference', evidenceIds: ['E7'] },
    ],
    funnel: [
      { name: 'Acquire', signal: 'Brand, technical content, website, launches, word of mouth', state: 'Known' },
      { name: 'Evaluate', signal: 'Free signup and first useful product task', state: 'Hypothesis' },
      { name: 'Activate', signal: 'Published product-specific 14- and 30-day behaviors', state: 'Known' },
      { name: 'Expand', signal: 'Cross-activation into multiple products and in-product checkout', state: 'Known' },
      { name: 'Retain', signal: 'Segment and product retention rates are unavailable', state: 'Missing data' },
    ],
  },
  benchmarkProfile: {
    category: 'Developer tools and product analytics',
    businessModel: 'B2B SaaS with usage-based expansion',
    gtmMotion: 'Product-led growth with selective sales assistance',
    companyStage: 'Scale-up',
    geography: 'Global',
    peers: [],
    metrics: [
      { name: 'Product-specific activation', definition: 'Completion of a meaningful behavior within a product-specific 14- or 30-day window.', observedRange: null, unit: 'percentage of qualified new accounts', evidenceIds: ['E8'], freshness: 'Definition is public; performance date is unavailable.', limitation: 'PostHog publishes definitions but no comparable cohort range. Internal product analytics and matched peer data are required.' },
      { name: 'Self-serve revenue share', definition: 'Revenue completed through an in-product checkout without a sales-led close.', observedRange: null, unit: 'percentage of revenue', evidenceIds: ['E10', 'E11'], freshness: 'Current public pages; reporting period is not disclosed.', limitation: 'A company-specific directional signal, not an industry benchmark or a complete measure of sales assistance.' },
    ],
    conventions: ['Free self-serve entry', 'Technical education and launch content', 'Feature-led comparison pages', 'Product-qualified sales assistance'],
    whitespace: ['Make the full ship → observe → iterate loop inspectable instead of describing it', 'Turn acknowledged product limitations into a participatory developer challenge', 'Measure whether unusual brand attention creates qualified activation rather than impressions'],
  },
  assumptions: [
    { id: 'A1', title: 'Positioning comprehension', statement: 'The shift from product analytics to a self-driving product platform creates evaluation uncertainty for some qualified developers.', confidence: 'Low', impact: 'High', evidenceIds: ['E1', 'E2', 'E3', 'E7'], whyItMatters: 'If qualified users already understand the expanded story, a new proof experience will not solve a meaningful bottleneck.', validation: 'Measure comprehension and target-task selection with 8–12 ICP evaluators before changing acquisition.' },
    { id: 'A2', title: 'Activation over demo volume', statement: 'Meaningful self-service activation and selective technical assistance are more valuable than maximizing booked demos.', confidence: 'High', impact: 'High', evidenceIds: ['E5', 'E8', 'E10'], whyItMatters: 'Optimizing for demo volume could conflict with PostHog’s product-led model and attract lower-intent conversations.', validation: 'Compare activated, assisted, and unassisted ICP cohorts using account quality, multi-product activation, expansion, and retention.' },
    { id: 'A3', title: 'Public proof changes behavior', statement: 'A transparent, participatory proof of the self-driving loop will create more qualified activation than a conventional feature walkthrough.', confidence: 'Low', impact: 'High', evidenceIds: ['E7', 'E9'], whyItMatters: 'This is the creative mechanism behind the recommended bet; the evidence supports brand fit, not performance.', validation: 'Run one facilitated prototype and one unmoderated version before production or distribution spend.' },
    { id: 'A4', title: 'Revenue baseline', statement: 'Approximately $57.5M ARR is a usable external planning reference, while the internal baseline remains unknown.', confidence: 'Low', impact: 'Medium', evidenceIds: ['E11', 'E12'], whyItMatters: 'A false baseline would make revenue targets and required pipeline math misleading.', validation: 'Replace with an authorized internal ARR and expansion target; otherwise omit revenue forecasts.' },
    { id: 'A5', title: 'Current funnel performance', statement: 'The highest-leverage loss occurs between evaluation and multi-product activation.', confidence: 'Low', impact: 'High', evidenceIds: ['E1', 'E3', 'E8'], whyItMatters: 'The recommended experiments should move to a different stage if acquisition, retention, or paid conversion is the actual constraint.', validation: 'Pull signup, first-team-event, saved-insight, replay-analysis, flag, experiment, checkout, and retention cohorts from PostHog and Stripe.' },
  ],
  operatingPlan: {
    decision: {
      problem: 'Test whether fixing one visible sandbox problem helps developers understand PostHog and use a second product.',
      evidenceIds: ['E1', 'E3', 'E7', 'E8'],
      intervention: 'Prototype a public proof where PostHog observes a real product problem, proposes a fix, and measures the result.',
      desiredOutcome: 'More qualified evaluators complete meaningful activation events across more than one PostHog product.',
      horizon: '21-day proof sprint after an 8–12 person comprehension baseline.',
      successMetric: 'Primary: multi-product activation within 30 days. Diagnostic: proof completion and qualified assistance requests.',
      baseline: null,
      target: null,
      assumptions: ['Evaluation-to-activation is the current constraint.', 'A public proof is consistent with PostHog’s brand.', 'Internal cohort data will replace illustrative planning inputs.'],
    },
    channels: [
      { channel: 'Paid media', decision: 'Hold', rationale: 'First find out whether the test works. Buy reach after that.', evidenceIds: ['E9'], dataNeeded: 'Incremental qualified activation and approved audience/privacy rules.' },
      { channel: 'Organic & SEO', decision: 'Investigate', rationale: 'Publish something developers can use before planning how to promote it.', evidenceIds: ['E9'], dataNeeded: 'Qualified search demand, task starts, activation, and assisted conversions.' },
      { channel: 'Email & lifecycle', decision: 'Investigate', rationale: 'Offer consented, behavior-triggered assistance when an evaluator stalls on an activation event.', evidenceIds: ['E8', 'E10'], dataNeeded: 'Current automations, trigger precision, replies, activation, and unsubscribe guardrails.' },
      { channel: 'Inbound & website', decision: 'Test', rationale: 'Make the self-driving promise inspectable through one live product loop.', evidenceIds: ['E5', 'E7'], dataNeeded: 'Path selection, first useful task, proof completion, and downstream activation.' },
      { channel: 'Community & developer relations', decision: 'Investigate', rationale: 'Invite a few developers to try it privately. Let them break it before the public does.', evidenceIds: ['E6', 'E9'], dataNeeded: 'Participant fit, completion, feedback, referrals, and moderation capacity.' },
      { channel: 'Partnerships & events', decision: 'Hold', rationale: 'The canary can wait. Prove the browser version works before building hardware.', evidenceIds: ['E10'], dataNeeded: 'Digital proof performance, partner quality, attributable activation, and production cost.' },
      { channel: 'Sales & CRM', decision: 'Investigate', rationale: 'Offer technical assistance to high-potential accounts based on product behavior.', evidenceIds: ['E10'], dataNeeded: 'Account potential, activation triggers, routing, assistance acceptance, and expansion.' },
    ],
  },
  commercialPlan: {
    northStar: 'Qualified multi-product activation',
    pipelineOutcome: 'More ICP-fit accounts reaching a meaningful second product and creating observable expansion or assisted-sales potential.',
    baseline: null,
    target: null,
    attributionWindow: '30 days from first qualified proof interaction',
    sourceOfTruth: 'Product analytics joined to account qualification, CRM assistance, checkout, and experiment exposure.',
    pipelineLogic: 'Qualified proof participants → first useful task → second-product activation → product-qualified account → assisted or self-serve expansion. Report counts and rates at every transition; do not convert activity into pipeline dollars without account-level value data.',
    costPrinciple: 'Estimate the resources required to produce, recruit, distribute, instrument, and measure each test. A proposed cap is test cost, not inferred CAC, available budget, or proof of affordability. Calculate CAC only after attributable spend and new customers are observed.',
    leadingIndicators: [
      { name: 'Proof completion', signal: 'Qualified participants complete the inspectable ship → observe → iterate task.', source: 'Experiment exposure and product events' },
      { name: 'Second-product activation', signal: 'A qualified account reaches a defined activation event in another product within 30 days.', source: 'Product analytics and account identity' },
      { name: 'Qualified assistance signal', signal: 'An ICP-fit account accepts technical assistance or crosses the agreed product-qualified threshold.', source: 'CRM and product-qualified account model' },
      { name: 'Expansion signal', signal: 'The account starts an attributable paid checkout or qualified expansion opportunity.', source: 'Checkout and CRM opportunity data' },
    ],
    guardrails: ['Activation quality must not decline in the test cohort.', 'Support burden and product error rates must stay within an agreed limit.', 'Brand attention without qualified task completion does not count as success.'],
    competitivePressures: [
      { id: 'C1', attacker: 'Focused product-analytics specialist', vulnerability: 'Platform breadth can make evaluation feel complex before a developer reaches value.', likelyMove: 'Position a narrower workflow as faster to understand and deploy than an expanding all-in-one platform.', evidenceIds: ['E1', 'E2', 'E3', 'E7'], threat: 'High', leadingSignal: 'Qualified evaluators select a narrow alternative after visiting comparison, pricing, or setup content.', response: 'Make one complete cross-product workflow easier to understand and finish than a specialist’s isolated feature demo.' },
      { id: 'C2', attacker: 'Bundled cloud or observability platform', vulnerability: 'Teams may accept an adequate bundled feature to avoid adding another vendor.', likelyMove: 'Bundle basic analytics, flags, or replay into an existing infrastructure contract and sell operational simplicity.', evidenceIds: ['E7'], threat: 'Medium', leadingSignal: 'Loss notes increasingly cite consolidation, procurement, or an existing platform bundle.', response: 'Measure and demonstrate the product-learning speed gained from integrated context, not feature-count superiority.' },
      { id: 'C3', attacker: 'Enterprise analytics suite', vulnerability: 'Public self-service strength may not answer governance and buying-group concerns for larger accounts.', likelyMove: 'Frame enterprise governance, predictability, and implementation services as safer than developer-led adoption.', evidenceIds: ['E6', 'E10'], threat: 'Medium', leadingSignal: 'High-potential accounts activate but stall before multi-team adoption or request governance proof.', response: 'Create evidence for a controlled technical-assistance path while preserving the self-service entry motion.' },
    ],
    defensibility: [
      { asset: 'Inspectable product loop', whyHardToCopy: 'It requires multiple products, shared context, instrumentation, and credible human review to work as a real demonstration.', proofNeeded: 'Show that qualified users complete the loop and activate a second product more often than a matched baseline.' },
      { asset: 'Developer trust through transparency', whyHardToCopy: 'Publishing failures and rejected automation requires operating behavior, not campaign language.', proofNeeded: 'Measure whether transparent artifacts increase qualified completion and return behavior without damaging confidence.' },
      { asset: 'Self-service plus selective assistance', whyHardToCopy: 'The combination requires product signals, account identity, routing, and technical sales judgment.', proofNeeded: 'Compare assisted and unassisted qualified cohorts on activation, expansion, and support cost.' },
    ],
    roadmap: [
      { horizon: '0–30 days', objective: 'Find the stuck step. Test one small fix.', decisionGate: 'Proceed only if target users understand the platform better and complete the defined task; establish the baseline before scaling.', experimentIds: ['O1'] },
      { horizon: '31–60 days', objective: 'Invite developers to prove us wrong.', decisionGate: 'Expand only if the mechanism creates useful product learning and qualified activation without failing trust or support guardrails.', experimentIds: ['O2'] },
      { horizon: '61–90 days', objective: 'Repeat what worked. Then earn the weird prop.', decisionGate: 'Fund the larger expression only when earlier cohorts show an attributable downstream account signal.', experimentIds: ['O3', 'O4'] },
    ],
  },
  opportunities: [
    { id: 'O1', priority: 'Now', territory: 'Product as proof', behavior: 'Help a developer complete one useful task, then try a second product.', title: 'One bug. Show your work.', hypothesis: 'Watching a problem get diagnosed, fixed, and checked might help developers understand the platform and use a second product.', evidenceIds: ['E6', 'E7', 'E8', 'E9'], counterEvidenceIds: ['E4'], stage: 'Activate', effort: 'Medium', action: 'Instrument a small open-source application, introduce one consented usability defect, let PostHog identify the signal and draft a fix, then publish the human-reviewed change and measured outcome.', metric: 'Proof completion and multi-product activation within 30 days, segmented by ICP fit.', validation: 'Run the story with 8–12 target developers. Establish existing comprehension and activation before comparing the prototype.', owner: 'Website + growth engineering', design: { channel: 'Inbound & website', ambition: 'Core', mechanism: 'Let people inspect the problem, the proposed fix, and what happened after it shipped.', differentBecause: 'Show the evidence, the uncertainty, and the human review. Keep the awkward bits in.', smallestTest: 'One synthetic app, one problem, one facilitated session, and a static trace before any public build.', budgetCap: 1000, durationDays: 21, stopRule: 'Stop if target developers cannot explain the platform more clearly after the proof or if the loop requires misleading automation claims.', primaryMetric: 'Qualified participants who start using a second product', guardrail: 'No production customer data, hidden code changes, or unsupported causal claims.' } },
    { id: 'O2', priority: 'Next', territory: 'Community competition', behavior: 'Invite developers to find where the workflow gets it wrong.', title: 'Break the hedgehog', hypothesis: 'An adversarial developer challenge can generate more useful product learning and qualified activation than a polished webinar.', evidenceIds: ['E6', 'E9'], counterEvidenceIds: ['E4'], stage: 'Discover', effort: 'Medium', action: 'Give invited developers a sandbox and ask them to create edge cases the self-driving workflow misdiagnoses. Publish the failures, fixes, and winner’s technical write-up.', metric: 'Qualified participants, valid failure cases, activated products, and participant-authored referrals.', validation: 'Run a five-person closed red-team session before making the challenge public.', owner: 'Developer relations + product', design: { channel: 'Community & developer relations', ambition: 'Bold', mechanism: 'Developers earn status by finding where automation fails, while PostHog earns trust by exposing and fixing those failures.', differentBecause: 'The company markets limitations and learning rather than staging a flawless demo.', smallestTest: 'Five developers, a private sandbox, one two-hour session, and no prize beyond public credit.', budgetCap: 2500, durationDays: 14, stopRule: 'Stop if the challenge attracts exploit behavior without useful learning or participants do not reach an activation event.', primaryMetric: 'Useful failures found by each qualified participant', guardrail: 'Sandbox only, responsible disclosure rules, participant consent, and no production access.' } },
    { id: 'O3', priority: 'Later', territory: 'Radical transparency', behavior: 'Give developers a reason to come back: useful mistakes, with receipts.', title: 'Things we shipped. Things we should not have.', hypothesis: 'Showing rejected AI suggestions and failed experiments might make the product claim more credible.', evidenceIds: ['E7', 'E9'], counterEvidenceIds: ['E4'], stage: 'Evaluate', effort: 'Medium', action: 'Publish a weekly machine-readable ledger showing what the agent proposed, what humans rejected, what shipped, what was reverted, and what changed in the metric.', metric: 'Qualified return visits, proof-to-product activation, technical citations, and assisted account activity.', validation: 'Publish one manually curated edition and interview readers about credibility and usefulness.', owner: 'Content + engineering', design: { channel: 'Organic & SEO', ambition: 'Bold', mechanism: 'Publish what the agent got wrong, what a human rejected, and what was learned.', differentBecause: 'Most launch content celebrates successes; this artifact makes judgment and reversals the product story.', smallestTest: 'One edition covering three real or clearly synthetic decisions with evidence and code links.', budgetCap: 750, durationDays: 14, stopRule: 'Stop if readers interpret the ledger as production instability or entries cannot be verified.', primaryMetric: 'Qualified readers who go on to use the product', guardrail: 'No confidential data, employee blame, customer exposure, or fabricated failures.' } },
    { id: 'O4', priority: 'Later', territory: 'Physical absurdity', behavior: 'Let someone ship, observe, and roll back a change using a strange little prop.', title: 'Canary in the deployment', hypothesis: 'A strange physical artifact connected to a sandbox can earn attention while teaching how safe releases and product signals work together.', evidenceIds: ['E7', 'E9', 'E10'], counterEvidenceIds: ['E4'], stage: 'Discover', effort: 'High', action: 'Prototype an animatronic canary whose behavior changes through a PostHog feature flag while a public dashboard shows exposure, errors, replays, and rollback.', metric: 'Completed safe-release tasks and subsequent product activation, separated from photos and scans.', validation: 'Test a browser-based simulation and paper prop with one developer meetup before building hardware.', owner: 'Brand + developer relations', design: { channel: 'Partnerships & events', ambition: 'Wildcard', mechanism: 'A deployment metaphor becomes a controllable physical object backed by real feature-flag and telemetry behavior.', differentBecause: 'The bird has a job: teach someone to ship and roll back a change. Photos alone do not count.', smallestTest: 'A browser animation, cardboard canary, ten invited participants, and no hardware fabrication.', budgetCap: 1500, durationDays: 21, stopRule: 'Stop if people remember the prop but cannot explain the safe-release workflow or attributable activation is absent.', primaryMetric: 'Qualified participants who finish a safe release', guardrail: 'No production control, accessible digital alternative, hard spend cap, and reusable materials.' } },
  ],
  unknowns: [
    'Which segment currently activates and retains best across multiple products?',
    'Where does the highest-value ICP cohort drop between signup and the first two activation events?',
    'How well do evaluators understand the new self-driving product positioning?',
    'What are current assisted and unassisted expansion rates?',
    'Which existing content, demos, or product experiences already address this thesis?',
  ],
};
