import {economicsMarkdown} from './economics';
import type {Opportunity,Report} from './types';
import type {ExecutionTask,Channel} from './operating';
export const adapters=[
 {id:'crm',name:'CRM',read:'Pipeline, account fit, qualification and lifecycle events',write:'Create a task or update an approved campaign record',status:'Not connected'},
 {id:'email',name:'Email',read:'Consented audiences, deliveries, replies and unsubscribes',write:'Create a draft sequence; sending requires explicit authorization',status:'Not connected'},
 {id:'organic',name:'Organic',read:'Search performance, content engagement and activation',write:'Create CMS drafts and a publishing schedule',status:'Not connected'},
 {id:'ppc',name:'Paid media',read:'Spend, campaign performance and qualified conversions',write:'Create paused campaigns with a hard budget cap',status:'Not connected'},
 {id:'analytics',name:'Product analytics',read:'Target-task completion, activation and retention',write:'Create measurement definitions and annotations',status:'Not connected'}
] as const;
export function executionPack(report:Report,o:Opportunity,schedule:{startDate:string;dueDate:string;owner:string;budgetCap:number},id:string):ExecutionTask{
 const d=o.design;const artifact=`# Execution pack: ${o.title}\n\nStatus: Prepared only. Nothing published, sent, booked or spent.\n\nCompany: ${report.brief.company}\nAudience: ${report.brief.audience}\nWorking objective: ${report.brief.objective}\n\n## Problem hypothesis\n${o.hypothesis}\n\n## Proposed treatment\n${o.action}\n${d?`\nMechanism: ${d.mechanism}\nDistinctive because: ${d.differentBecause}\nSmallest test: ${d.smallestTest}\n`:''}\n## Delivery contract\nOwner: ${schedule.owner}\nStart: ${schedule.startDate}\nReview due: ${schedule.dueDate}\nMaximum proposed spend: USD ${schedule.budgetCap}\nChannel: ${d?.channel??'Inbound & website'}\n\n## Deliverable checklist\n1. Verify the linked evidence and whether an equivalent solution exists.\n2. Produce the assets described in the proposed treatment; review them with the target audience.\n3. Configure a draft in the appropriate channel tool after connecting it.\n4. Verify audience permissions, tracking, baseline, target and stop rule.\n5. Obtain explicit approval for the exact audience, assets, schedule and spending cap.\n6. Launch through a connected adapter, retain the provider receipt and review outcomes.\n\n## Measurement\nPrimary metric: ${d?.primaryMetric??o.metric}\nValidation: ${o.validation}\nStop rule: ${d?.stopRule??'Define before external launch.'}\nGuardrail: ${d?.guardrail??'Define before external launch.'}\n\n## Evidence\n${report.evidence.filter(e=>[...o.evidenceIds,...o.counterEvidenceIds].includes(e.id)).map(e=>`- ${e.id}: ${e.summary}\n  ${e.url}\n  Limitation: ${e.limitation}`).join('\n')}\n\nExternal adapters are not connected. This pack is executable preparation, not proof of campaign launch.\n`;
 const createdAt=new Date().toISOString();
 return {id,experimentId:o.id,title:o.title,channel:(d?.channel??'Inbound & website') as Channel,owner:schedule.owner,startDate:schedule.startDate,dueDate:schedule.dueDate,budgetCap:schedule.budgetCap,status:'Prepared',artifact:artifact+economicsMarkdown((report.economics??[]).filter(m=>m.experimentId===o.id)),createdAt,approvedAt:createdAt,approvalScope:'Prepare only'};
}
