import type { Report, Opportunity } from './types';

const concepts = [
  {
    title: 'Let buyers build their own proof map', role: 'Convert', channel: 'Sales & CRM',
    hypothesis: 'A buyer may find relevant proof faster when starting with their own business problem.',
    action: 'Prototype three paths through existing, approved client stories. Each path shows the problem, the work, the reported result, and what would be different for this buyer.',
    mechanism: 'The buyer chooses a problem and leaves with a one-page decision brief they can discuss internally, using Stratabeat’s existing client proof.',
    convention: 'A static wall of case studies.', metric: 'Qualified opportunities created from discovery calls within 60 days.',
    early: 'Can five willing target buyers find relevant proof and explain the next step without help?',
    stop: 'Revise if fewer than three of five buyers can explain why the selected proof is relevant. Do not infer sales lift from five interviews.',
    cost: 1200, days: 21, costNote: 'Illustrative total: 12 design hours at $75 plus $300 for research incentives. Confirm rates and availability.',
  },
  {
    title: 'Test whether buyers can tell competitors apart', role: 'Acquire', channel: 'Inbound & website',
    hypothesis: 'Some target companies may have messages that buyers cannot distinguish from competitors.',
    action: 'With permission, remove logos from three competing messages. Ask target buyers to match each message to the right company, then explain their choice. Present the blind result alongside one proposed rewrite.',
    mechanism: 'Use Stratabeat’s audience research and behavioral approach to make a prospect experience the cost of indistinct messaging before discussing a project.',
    convention: 'An unsolicited website audit with a generic score.', metric: 'Qualified opportunities from participating target accounts within 60 days.',
    early: 'Do target buyers confuse the messages, and does the prospect accept that this is worth investigating?',
    stop: 'Stop if the messages are already distinct or participating companies do not see a business reason to act.',
    cost: 1800, days: 30, costNote: 'Illustrative total: 16 research hours at $75 plus $600 for participant recruitment.',
  },
  {
    title: 'Rebuild one missing buyer shortlist', role: 'Build authority', channel: 'Organic & SEO',
    hypothesis: 'A company may be missing from the places a particular buyer checks before contacting a vendor.',
    action: 'Ask a willing prospect for one real buying question. Record what appears in search, AI answers and relevant discussions on a stated date. Test one missing proof asset and repeat the same checks.',
    mechanism: 'Combine Stratabeat’s search, AI visibility and Reddit services around one buyer decision, with a visible record of changes and uncertainty.',
    convention: 'A broad visibility index with no buyer decision attached.', metric: 'Qualified opportunities that cite the tested buying question or proof asset within 90 days.',
    early: 'Does the company appear in repeated checks of the same question? Record variation rather than claiming a stable ranking.',
    stop: 'Pause if the question has no buyer relevance or improved visibility produces no qualified interest during the review window.',
    cost: 1500, days: 30, costNote: 'Illustrative total: 18 specialist hours at $75 plus $150 for tools.',
  },
  {
    title: 'Show clients how a rival could win', role: 'Retain', channel: 'Email & lifecycle',
    hypothesis: 'A concrete competitive challenge may help an existing client see where continued work is useful.',
    action: 'Choose one consenting client and one documented competitor move. Show how it could influence a buying decision, then let the client choose whether to test a response.',
    mechanism: 'A private decision exercise using the client’s approved performance data and Stratabeat’s audience and conversion expertise, rather than a routine activity recap.',
    convention: 'A quarterly report listing tasks completed.', metric: 'Renewed contract value at the client’s next scheduled renewal; record other influences.',
    early: 'Does the client agree the issue matters and approve a response?',
    stop: 'Drop the threat if evidence does not support it. Do not manufacture fear to defend a renewal.',
    cost: 600, days: 30, costNote: 'Illustrative total: eight strategist hours at $75. Renewal results may take longer than this pilot.',
  },
  {
    title: 'Let a client inspect the next service before buying', role: 'Expand', channel: 'Sales & CRM',
    hypothesis: 'An existing client may consider another service after seeing a small, relevant piece of work.',
    action: 'For one consenting SEO client with a verified conversion issue, build a small CRO prototype with the specialist who would deliver it. Agree the buying criterion before demonstrating it.',
    mechanism: 'Use the agency’s existing search-to-conversion service combination to demonstrate a specific next step in the client’s own journey.',
    convention: 'A cross-sell deck listing additional services.', metric: 'Signed expansion contract value within 90 days; exclude previously agreed work.',
    early: 'Does the client request a scoped proposal after reviewing the prototype?',
    stop: 'Stop if the client has no validated conversion problem, no interest, or no delivery capacity to use the service.',
    cost: 900, days: 21, costNote: 'Illustrative total: 12 specialist hours at $75. Confirm scope before offering free work.',
  },
] as const;
const opportunities: Opportunity[] = concepts.map((c, i) => ({
  id: `O${i + 1}`, title: c.title, hypothesis: c.hypothesis,
  evidenceIds: ['E1'], counterEvidenceIds: [], stage: i === 3 ? 'Retain' : 'Evaluate',
  effort: 'Low', priority: 'Later',
  territory: c.role, behavior: c.early, action: c.action, metric: c.metric,
  validation: `${c.early} ${c.costNote} Confirm current performance and whether this already exists before launch.`,
  owner: 'Proposed: account lead and relevant specialist',
  design: { channel: c.channel, ambition: i === 1 ? 'Bold' : 'Core', commercialRole: c.role,
    categoryConvention: c.convention, brandFit: 'Fits the agency’s stated audience research, conversion and organic growth services.',
    mechanism: c.mechanism, differentBecause: c.mechanism, assumptionToTest: c.hypothesis,
    proofRequired: c.early, smallestTest: c.action, budgetCap: c.cost, durationDays: c.days,
    primaryMetric: c.metric, stopRule: c.stop,
    guardrail: 'Use approved client material only. Separate reported results from predictions. Track delivery hours and avoid displacing paid client work.' },
}));

export const stratabeatExample: Report = {
  brief: { company: 'Stratabeat', website: 'https://stratabeat.com/', audience: 'Working assumption: marketing leaders at B2B SaaS and tech companies evaluating an organic growth agency.', objective: 'Explore five small tests that could help win, retain or expand suitable client accounts.', constraints: 'Interview case only. No CRM, sales calls, client records or budget access. All experiments and costs are proposals.', industry: 'B2B marketing services', businessModel: 'Client services; contract terms unknown', gtmMotion: 'Assumed consultative sales', geography: 'Not established', companyStage: 'Established agency; internal scale unknown' },
  summary: 'Stratabeat already has testimonials and searchable case studies. The previous first recommendation is withdrawn pending a complete website review.',
  decisionBrief: {
    finding: 'Stratabeat already has testimonials and searchable case studies. We have not established a gap that justifies another proof format.',
    status: 'Needs data', evidenceIds: ['E3', 'E4'],
    whyItMatters: 'Relevant proof could help a buyer agree on a next step. We do not know whether proof is currently a sales obstacle.',
    alternativeExplanations: ['Current case studies may already do this well.', 'Budget, timing or poor client fit could matter more than proof.'],
    recommendedExperimentId: null,
    whyFirst: 'No experiment is prioritized. Review the navigation and existing work before reassessing these five conditional ideas.',
    nextQuestion: 'Which relevant pages and existing services have we inspected, and what specific opportunity remains after that review?',
  },
  evidence: [
    { id: 'E3', title: 'Existing client testimonials', url: 'https://stratabeat.com/why-stratabeat/testimonials/', summary: 'Stratabeat has a dedicated client testimonials section.', kind: 'positive', date: null, limitation: 'Public company-published proof. This does not measure conversion performance.' },
    { id: 'E4', title: 'Existing case-study library', url: 'https://stratabeat.com/results/', summary: 'The company publishes case studies with service categories and keyword search.', kind: 'positive', date: null, limitation: 'The existing library contradicts a simple missing-proof claim. Buyer friction has not been established.' },
    { id: 'E1', title: 'Stratabeat: services and client proof', url: 'https://stratabeat.com/', summary: 'The agency presents organic growth services and client stories for B2B companies.', kind: 'positive', date: null, limitation: 'Company-published material reviewed September 28, 2026. It does not establish sales performance or a proof gap.' },
    { id: 'E2', title: 'Tom Shapiro: books and speaking', url: 'https://tomshapiro.com/', summary: 'Tom’s site features books, speaking and a link to Stratabeat.', kind: 'context', date: null, limitation: 'Company-controlled source reviewed September 28, 2026. It does not quantify Tom’s contribution to pipeline or establish founder dependence.' },
  ],
  opportunities, unknowns: ['Which clients are the best fit and most profitable?', 'Where do suitable prospects stop, and why?', 'What are current win, renewal and expansion rates?', 'Which of these approaches already exist?', 'What budget and delivery capacity could support a pilot?'],
  generatedAt: '2026-09-28T00:00:00.000Z', mode: 'example',
  warnings: ['The prior first recommendation was withdrawn. All five ideas are conditional and require website review.', 'Outside-in interview example, not a live AI run or internal diagnosis.', 'The initial two-page review missed directly discoverable proof pages. Independent customer evidence is still needed.', 'Costs are illustrative scoped estimates, not company budgets. No revenue lift or causal effect has been measured.'],
};
