'use client';

import { ArrowRight, CheckCircle2, CircleHelp, Gauge, Lightbulb, PlugZap, Radar, ShieldCheck, Sparkles, Target } from 'lucide-react';
import type { Opportunity, Report } from '@/lib/gtm/types';
import { adapters } from '@/lib/gtm/execution';
import { channels, evaluateOutcome, type Operations } from '@/lib/gtm/operating';

type Navigate = (tab: string) => void;

function EvidenceButton({ ids, onEvidence }: { ids: string[]; onEvidence: (ids: string[]) => void }) {
  return ids.length ? <button className="v3-evidence-link" onClick={() => onEvidence(ids)}>{ids.join(', ')} ↗</button> : <span className="v3-evidence-link muted">Evidence needed</span>;
}

export function CommandCenter({ report, onNavigate, onEvidence }: { report: Report; onNavigate: Navigate; onEvidence: (ids: string[]) => void }) {
  const decision = report.operatingPlan?.decision;
  const recommended = report.opportunities.find(item => item.priority === 'Now') ?? report.opportunities[0];
  const risky = (report.assumptions ?? []).filter(item => item.impact === 'High' && item.confidence === 'Low');
  const immediateCap = recommended?.design?.budgetCap;
  return <div className="v3-stack">
    <section className="v3-hero">
      <div className="v3-hero-copy"><p className="eyebrow">PORTFOLIO THESIS · DECISION REQUIRED</p><h2>{report.marketContext?.thesis ?? report.summary}</h2><p>{decision?.problem ?? report.brief.objective}</p><div className="v3-hero-actions"><button className="v3-light-button" onClick={() => onNavigate('plan')}>Inspect the bet <ArrowRight size={16}/></button><button className="v3-ghost-button" onClick={() => onNavigate('strategy')}>Challenge assumptions</button></div></div>
      <div className="v3-recommendation"><span><Target size={16}/> Recommended now</span><h3>{recommended?.title ?? 'Collect enough evidence to define a test'}</h3><p>{recommended?.behavior ?? recommended?.hypothesis ?? 'Do not allocate channel spend until the bottleneck is observable.'}</p><dl><div><dt>Time to signal</dt><dd>{recommended?.design ? `${recommended.design.durationDays} days` : 'Unknown'}</dd></div><div><dt>Proposed cap</dt><dd>{recommended?.design?.budgetCap == null ? 'Pending' : `$${recommended.design.budgetCap.toLocaleString()}`}</dd></div><div><dt>Decision state</dt><dd>Validate first</dd></div></dl></div>
    </section>

    <section className="v3-kpi-row" aria-label="Decision readiness">
      <div><Gauge size={18}/><strong>{risky.length}</strong><span>critical assumptions</span></div>
      <div><Radar size={18}/><strong>Missing</strong><span>funnel baseline</span></div>
      <div><Sparkles size={18}/><strong>{recommended?.design?.durationDays ?? '—'}d</strong><span>time to signal</span></div>
      <div><ShieldCheck size={18}/><strong>{immediateCap == null ? 'Pending' : `$${immediateCap.toLocaleString()}`}</strong><span>immediate test cap</span></div>
    </section>

    <section className="panel v3-funnel-panel"><div className="v3-section-heading"><div><p className="eyebrow">FUNNEL DIAGNOSIS</p><h2>Where the thesis could break</h2></div><span className="v3-status hypothesis">Outside-in hypothesis</span></div><div className="v3-funnel">{(report.marketContext?.funnel ?? []).map((stage, index) => <div className="v3-funnel-stage" key={stage.name}><span>0{index + 1}</span><h3>{stage.name}</h3><p>{stage.signal}</p><small className={`v3-state ${stage.state.toLowerCase().replace(' ', '-')}`}>{stage.state}</small></div>)}</div></section>

    <div className="v3-command-grid">
      <section className="panel"><div className="v3-section-heading"><div><p className="eyebrow">NOW / NEXT / LATER</p><h2>Sequenced, not scattered</h2></div><button onClick={() => onNavigate('plan')}>Full portfolio ↗</button></div><div className="v3-sequence">{report.opportunities.map(item => <button key={item.id} onClick={() => onNavigate('plan')}><span>{item.priority ?? 'Later'}</span><b>{item.title}</b><small>{item.territory ?? item.design?.ambition ?? item.stage}</small></button>)}</div></section>
      <section className="panel v3-risk-panel"><p className="eyebrow">WHAT CHANGES THE DECISION</p><h2>Disprove these first</h2>{risky.map(item => <div className="v3-risk" key={item.id}><span>{item.id}</span><div><b>{item.title}</b><p>{item.validation}</p><EvidenceButton ids={item.evidenceIds} onEvidence={onEvidence}/></div></div>)}{!risky.length && <p className="muted">No high-impact, low-confidence assumptions recorded.</p>}</section>
    </div>
  </div>;
}

export function StrategyView({ report, onEvidence }: { report: Report; onEvidence: (ids: string[]) => void }) {
  const plans = report.operatingPlan?.channels ?? channels.map(channel => ({ channel, decision: 'Investigate' as const, rationale: 'Research before allocating effort.', evidenceIds: [], dataNeeded: 'Baseline and audience behavior.' }));
  const benchmark = report.benchmarkProfile;
  const groups = ['Test', 'Investigate', 'Hold'] as const;
  const assumptions = [...(report.assumptions ?? [])].sort((a, b) => Number(b.impact === 'High') - Number(a.impact === 'High') || Number(b.confidence === 'Low') - Number(a.confidence === 'Low'));
  return <div className="v3-stack">
    <div className="v3-section-heading"><div><p className="eyebrow">STRATEGY / SOURCE OF TRUTH</p><h2>What we know, infer, and still need</h2><p className="muted">Every strategic input carries its epistemic status. Assumptions stay visible until internal data replaces them.</p></div></div>
    <section className="v3-fact-grid">{(report.marketContext?.facts ?? []).map(item => <article className="panel v3-fact" key={item.label}><div><span className={`v3-status ${item.status.toLowerCase().replace(' ', '-')}`}>{item.status}</span><EvidenceButton ids={item.evidenceIds} onEvidence={onEvidence}/></div><h3>{item.label}</h3><p>{item.value}</p></article>)}</section>
    <section className="panel v3-benchmark"><div className="v3-section-heading"><div><p className="eyebrow">BENCHMARK COHORT</p><h2>Compare the mechanism, then find the whitespace</h2><p className="muted">Ranges stay empty until a source establishes the metric definition, cohort, period, and comparable range.</p></div><span className="v3-status hypothesis">{benchmark ? 'Cohort hypothesis' : 'Needs research'}</span></div>{benchmark ? <><div className="v3-cohort-row"><span>{benchmark.category}</span><span>{benchmark.businessModel}</span><span>{benchmark.gtmMotion}</span><span>{benchmark.companyStage}</span><span>{benchmark.geography}</span></div><div className="v3-benchmark-grid"><div><h3>Peer roles</h3>{benchmark.peers.map(peer => <article key={`${peer.company}-${peer.role}`}><b>{peer.company}</b><small>{peer.role}</small><p>{peer.rationale}</p><EvidenceButton ids={peer.evidenceIds} onEvidence={onEvidence}/></article>)}{!benchmark.peers.length && <p className="muted">No defensible peer set yet. A live run must source direct, category, motion, and creative references.</p>}</div><div><h3>Comparable metrics</h3>{benchmark.metrics.map(metric => <article key={metric.name}><b>{metric.name}</b><strong>{metric.observedRange ?? 'Range unavailable'}</strong><p>{metric.definition}</p><small>{metric.freshness} · {metric.limitation}</small><EvidenceButton ids={metric.evidenceIds} onEvidence={onEvidence}/></article>)}</div><div><h3>Category conventions</h3><ul>{benchmark.conventions.map(item => <li key={item}>{item}</li>)}</ul></div><div><h3>Strategic whitespace</h3><ul>{benchmark.whitespace.map(item => <li key={item}>{item}</li>)}</ul></div></div></> : <p className="muted">Classify the company by category, business model, GTM motion, stage, geography, and buyer behavior before comparing it with peers.</p>}</section>
    <section><div className="v3-section-heading"><div><p className="eyebrow">CHANNEL ALLOCATION</p><h2>Seven channels, three decisions</h2></div></div><div className="v3-channel-groups">{groups.map(group => <section className={`v3-channel-group ${group.toLowerCase()}`} key={group}><header><strong>{group}</strong><span>{plans.filter(item => item.decision === group).length}</span></header>{plans.filter(item => item.decision === group).map(item => <article key={item.channel}><h3>{item.channel}</h3><p>{item.rationale}</p><details><summary>Data required</summary><p>{item.dataNeeded}</p><EvidenceButton ids={item.evidenceIds} onEvidence={onEvidence}/></details></article>)}</section>)}</div></section>
    <section><div className="v3-section-heading"><div><p className="eyebrow">ASSUMPTION MAP</p><h2>The thesis under pressure</h2></div><span>{assumptions.filter(a => a.impact === 'High' && a.confidence === 'Low').length} require validation now</span></div><div className="v3-assumptions">{assumptions.map((item, index) => <details className="panel" key={item.id} open={index === 0 && item.impact === 'High'}><summary><span>{item.id}</span><div><b>{item.title}</b><small>{item.statement}</small></div><div className="v3-assumption-tags"><em>{item.impact} impact</em><em>{item.confidence} confidence</em></div></summary><div className="v3-assumption-body"><div><b>Why it matters</b><p>{item.whyItMatters}</p></div><div><b>Validation</b><p>{item.validation}</p><EvidenceButton ids={item.evidenceIds} onEvidence={onEvidence}/></div></div></details>)}</div></section>
  </div>;
}

export function ExperimentsView({ report, editable, onEdit, onEvidence }: { report: Report; editable: boolean; onEdit: (item: Opportunity) => void; onEvidence: (ids: string[]) => void }) {
  return <div className="v3-stack"><div className="v3-section-heading"><div><p className="eyebrow">CREATIVE PORTFOLIO</p><h2>Safe core. Bold proof. Controlled weirdness.</h2><p className="muted">Each concept must change a specific behavior, survive a cheap test, and stop before novelty becomes waste.</p></div></div>
    <section className="panel v3-portfolio-map"><div className="v3-map-axis y">Bolder idea</div><div className="v3-map-axis x">More operational complexity →</div>{report.opportunities.map((item, index) => { const ambition = item.design?.ambition ?? 'Core'; const top = ambition === 'Wildcard' ? 12 : ambition === 'Bold' ? 38 : 68; const effort = item.effort === 'High' ? 72 : item.effort === 'Medium' ? 49 : 25; const left = effort + index * 3; return <button key={item.id} style={{ top: `${top}%`, left: `${Math.min(left, 82)}%` }} title={item.title}><span>{item.id}</span><b>{item.title}</b></button>; })}<div className="v3-safe-zone">Start here</div></section>
    <div className="v3-experiment-list">{report.opportunities.map((item, index) => <details className={`panel v3-experiment ${item.priority === 'Now' ? 'is-now' : ''}`} key={item.id} open={item.priority === 'Now' || (!item.priority && index === 0)}><summary><div className="v3-experiment-index"><span>{item.id}</span><em>{item.priority ?? 'Unsequenced'}</em></div><div><p>{item.territory ?? item.design?.channel ?? item.stage}</p><h3>{item.title}</h3><small>{item.behavior ?? item.hypothesis}</small></div><div className="v3-experiment-meta"><span className={`ambition ${(item.design?.ambition ?? 'Core').toLowerCase()}`}>{item.design?.ambition ?? 'Core'}</span><span>{item.design?.durationDays ?? '—'} days</span><span>{item.design?.budgetCap == null ? 'Cap pending' : `$${item.design.budgetCap.toLocaleString()} cap`}</span></div></summary><div className="v3-experiment-body"><div className="v3-mechanism"><Lightbulb size={20}/><div><b>Mechanism</b><p>{item.design?.mechanism ?? item.action}</p><small>{item.design?.differentBecause}</small></div></div><div className="v3-spec-grid"><div><b>Smallest disproof</b><p>{item.design?.smallestTest ?? item.validation}</p></div><div><b>Primary signal</b><p>{item.design?.primaryMetric ?? item.metric}</p></div><div><b>Stop rule</b><p>{item.design?.stopRule ?? 'Define before launch.'}</p></div><div><b>Guardrail</b><p>{item.design?.guardrail ?? 'Human approval required.'}</p></div><div><b>Owner</b><p>{item.owner}</p></div><div><b>Evidence boundary</b><EvidenceButton ids={item.evidenceIds} onEvidence={onEvidence}/><p>Counter: {item.counterEvidenceIds.join(', ') || 'none recorded'}</p></div></div><button className="secondary" disabled={!editable} onClick={() => onEdit(item)}>Edit experiment</button></div></details>)}</div>
  </div>;
}

export function OperationsView({ report, operations, canPrepare, onPrepare }: { report: Report; operations: Operations; canPrepare: boolean; onPrepare: (opportunity: Opportunity) => void }) {
  return <div className="v3-stack"><div className="v3-section-heading"><div><p className="eyebrow">OPERATIONS</p><h2>Turn one approved bet into controlled work</h2><p className="muted">Strategy enters the queue only with an owner, artifact, window, cap, measurement plan, and human approval.</p></div></div>
    <div className="v3-ops-grid"><section className="v3-op-queue">{report.opportunities.filter(item => item.priority === 'Now' || operations.tasks.some(task => task.experimentId === item.id)).map(item => { const task = operations.tasks.find(task => task.experimentId === item.id); return <article className={`panel v3-op-card ${item.priority === 'Now' ? 'is-now' : ''}`} key={item.id}><div className="v3-op-head"><span>{item.priority ?? 'Queue'}</span><span>{task ? task.status : 'Awaiting approval'}</span></div><h3>{item.title}</h3><p>{item.action}</p><div className="v3-op-checks"><span className={item.owner ? 'done' : ''}><CheckCircle2 size={15}/> Owner</span><span className={item.design?.primaryMetric ? 'done' : ''}><CheckCircle2 size={15}/> Signal</span><span className={item.design?.stopRule ? 'done' : ''}><CheckCircle2 size={15}/> Stop rule</span><span className={item.design?.budgetCap != null ? 'done' : ''}><CheckCircle2 size={15}/> Cap</span></div>{task ? <div className="v3-task"><b>{task.owner}</b><span>{task.startDate} → {task.dueDate}</span><span>Cap ${task.budgetCap.toLocaleString()}</span><small>{task.approvedAt ? `Preparation approved ${new Date(task.approvedAt).toLocaleDateString()}` : 'Legacy pack · approval timestamp unavailable'}</small></div> : <button disabled={!canPrepare} onClick={() => onPrepare(item)}>Approve &amp; prepare execution pack</button>}</article>; })}<p className="v3-backlog-note">{report.opportunities.filter(item => item.priority !== 'Now').length} future concepts remain in Ideas until the current bet is reviewed.</p></section>
      <aside className="panel v3-operating-rule"><CircleHelp size={22}/><h2>Human decision gate</h2><p>No connector can publish or spend from a strategy card. The prepared pack is the review boundary.</p><ol><li>Verify the baseline</li><li>Approve audience and artifact</li><li>Approve cap and schedule</li><li>Connect the destination</li><li>Record the outcome</li></ol></aside></div>
    <details className="panel v3-integrations"><summary><span><PlugZap size={18}/> Integration readiness</span><small>CRM, product analytics, lifecycle, paid, organic, and community adapters</small></summary><div className="v3-adapter-grid">{adapters.map(adapter => <div key={adapter.id}><b>{adapter.name}</b><p>{adapter.read}</p><span>{adapter.status}</span></div>)}</div></details>
    {operations.outcomes.length > 0 && <section className="panel"><h2>Measured outcomes</h2>{operations.outcomes.map(outcome => { const result = evaluateOutcome(outcome); return <div className="v3-outcome" key={outcome.id}><b>{outcome.metric}</b><span>{result.baseline.toFixed(1)}% → {result.test.toFixed(1)}%</span><strong>{result.verdict}</strong><small>{result.limitation}</small></div>; })}</section>}
  </div>;
}
