'use client';
import {useState} from 'react';
import {caseCopy} from '@/lib/gtm/posthog-presentation';
import type {Report} from '@/lib/gtm/types';
import {calculateEconomics,emptyEconomics,illustrativeEconomics,type Economics} from '@/lib/gtm/economics';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
const money=(n:number|null)=>n===null?'Not modeled':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const number=(n:number|null)=>n===null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n);
function Numeric({label,value,onChange,max=1e9}:{label:string;value:number|null;onChange:(v:number|null)=>void;max?:number}){return <label className="econ-field">{label}<input type="number" min="0" max={max} step="any" placeholder="Unknown" value={value??''} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/></label>;}
export function PipelineBudget({report,canSave,onSave}:{report:Report;canSave:boolean;onSave:(m:Economics)=>Promise<void>}){
 const [selected,setSelected]=useState(report.opportunities[0]?.id??'');
 const opportunity=report.opportunities.find(o=>o.id===selected)??report.opportunities[0];
 if(!opportunity)return <section className="panel"><h2>Pipeline & Budget</h2><p>Add a proposed experiment to model its costs and commercial impact.</p></section>;
 return <section className="economics"><div className="section-title"><div><p className="eyebrow">INVESTMENT WORKBENCH · USD</p><h2>{caseCopy(report, 'What could this test change?', 'Cool idea. What does it cost?')}</h2><p className="muted">{caseCopy(report, 'Cost the idea. Model the incremental outcome. Decide what evidence earns the next investment.', 'Price the experiment. Change the assumptions. See what has to happen for it to be worth another dollar.')}</p></div><Select value={opportunity.id} onValueChange={setSelected}><SelectTrigger aria-label="Select experiment"><SelectValue/></SelectTrigger><SelectContent>{report.opportunities.map(o=><SelectItem key={o.id} value={o.id}>{o.id} · {o.title}</SelectItem>)}</SelectContent></Select></div><ModelEditor key={opportunity.id+JSON.stringify(report.economics?.find(m=>m.experimentId===opportunity.id))} initial={report.economics?.find(m=>m.experimentId===opportunity.id)??emptyEconomics(opportunity.id)} cap={opportunity.design?.budgetCap??null} canSave={canSave} onSave={onSave}/></section>;
}
function ModelEditor({initial,cap,canSave,onSave}:{initial:Economics;cap:number|null;canSave:boolean;onSave:(m:Economics)=>Promise<void>}){
 const [m,setM]=useState(initial),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const update=(patch:Partial<Economics>)=>{setM(old=>({...old,...patch}));setDirty(true);setError('');};
 let result:ReturnType<typeof calculateEconomics>|null=null;let invalid='';try{result=calculateEconomics(m);}catch{invalid='Use nonnegative amounts, rates between 0–100%, whole sample sizes, and a 1–730 day window.';}
 const base=result?.scenarios.find(s=>s.name==='Base');
 return <><div className="econ-toolbar"><span className="badge">{m.illustrative?'Synthetic illustration · not company data':'Assumption model · not measured results'}{dirty?' · unsaved':''}</span><button className="secondary" onClick={()=>update(illustrativeEconomics(m.experimentId))}>Load teaching example</button><button className="secondary" onClick={()=>update(emptyEconomics(m.experimentId))}>Clear inputs</button></div>
 <div className="econ-kpis">{[['Cash required',money(result?.cash??null)],['Including internal time',money(result?.total??null)],[m.motion==='Sales-led'?'Base incremental pipeline':'Base incremental paid customers',m.motion==='Sales-led'?money(base?.pipeline??null):number(base?.customers??null)],['Base expected bookings',money(base?.bookings??null)]].map(([label,value])=><article className="panel" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
 <p className="muted">Pipeline is opportunity value, not revenue. Bookings are modeled contract value, not recognized revenue or profit. Fractional customers are expectations.</p>
 <div className="econ-columns"><section className="panel"><h3>1. Scope the investment</h3><p>Estimate this experiment independently of company revenue. All amounts are USD.</p><div className="econ-costs">{m.costs.map((c,i)=><div className="econ-cost" key={i}><label className="econ-field">Line item<input aria-label={'Cost label '+(i+1)} value={c.label} onChange={e=>update({costs:m.costs.map((x,j)=>j===i?{...x,label:e.target.value}:x)})}/></label><Select value={c.kind} onValueChange={v=>update({costs:m.costs.map((x,j)=>j===i?{...x,kind:v as 'Cash'|'Internal time'}:x)})}><SelectTrigger aria-label={'Cost type '+(i+1)}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Cash">Cash</SelectItem><SelectItem value="Internal time">Internal time</SelectItem></SelectContent></Select><Numeric label="Units / hours" value={c.quantity} onChange={v=>update({costs:m.costs.map((x,j)=>j===i?{...x,quantity:v}:x)})}/><Numeric label="USD per unit" value={c.unitCost} onChange={v=>update({costs:m.costs.map((x,j)=>j===i?{...x,unitCost:v}:x)})}/><span>{money(c.quantity!==null&&c.unitCost!==null?c.quantity*c.unitCost:null)}</span><button className="secondary" disabled={m.costs.length===1} aria-label={'Remove cost '+(i+1)} onClick={()=>update({costs:m.costs.filter((_,j)=>j!==i)})}>Remove</button></div>)}</div><button className="secondary" disabled={m.costs.length>=20} onClick={()=>update({costs:[...m.costs,{label:'Additional cost',kind:'Cash',quantity:null,unitCost:null}]})}>Add cost</button><Numeric label="Cash available for this test (optional)" value={m.availableBudget} onChange={v=>update({availableBudget:v})}/><p className="muted">Existing idea cap: {cap===null?'Not set':money(cap)}. This model does not change that cap or authorize spending.</p>{result?.cash!==null&&result?.cash!==undefined&&cap!==null&&result.cash>cap&&<p className="error">Cash estimate exceeds the idea cap. Reconcile it before preparing execution.</p>}</section>
 <section className="panel"><h3>2. Define the causal hypothesis</h3><label className="econ-field">Commercial path<Select value={m.motion} onValueChange={v=>update({motion:v as Economics['motion'],scenarios:m.scenarios.map(s=>({...s,downstreamRate:null,winRate:null,value:null}))})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Sales-led">Sales-led</SelectItem><SelectItem value="Self-service">Self-service</SelectItem></SelectContent></Select></label><Numeric label="Qualified accounts exposed to the test" value={m.cohort} onChange={v=>update({cohort:v})}/><Numeric label="Baseline activation rate (%)" max={100} value={m.baselineRate} onChange={v=>update({baselineRate:v})}/><label className="econ-field">Assumption provenance and cohort definition<textarea value={m.assumptions} onChange={e=>update({assumptions:e.target.value})} placeholder="Who qualifies? Where do these inputs come from? Define activation and contract value period."/></label><p className="muted">We compare the same-size cohort with and without the test. Only activation changes; downstream conversion is held constant within each scenario. These are sensitivity cases, not confidence intervals.</p>{m.illustrative&&<button className="secondary" onClick={()=>update({illustrative:false})}>I replaced the teaching inputs with my assumptions</button>}</section></div>
 <section className="panel"><h3>3. Compare commercial scenarios</h3><p>Enter rates conditional on the preceding stage. For self-service, value means first-contract bookings per new paid account, not lifetime value.</p><div className="econ-table-wrap"><table className="econ-table"><caption>Editable assumptions and calculated incremental outcomes</caption><thead><tr><th>Scenario</th><th>Test activation %</th><th>{m.motion==='Sales-led'?'Activated → opportunity %':'Activated → paid %'}</th>{m.motion==='Sales-led'&&<th>Opportunity → won %</th>}<th>{m.motion==='Sales-led'?'Value per opportunity (USD)':'First contract value (USD)'}</th><th>Extra activated</th><th>{m.motion==='Sales-led'?'Extra opportunities':'Extra paid accounts'}</th>{m.motion==='Sales-led'&&<th>Pipeline</th>}<th>Bookings</th><th>Cost / extra {m.motion==='Sales-led'?'opportunity':'paid account'}</th></tr></thead><tbody>{m.scenarios.map((s,i)=>{const r=result?.scenarios[i];const change=(key:'activationRate'|'downstreamRate'|'winRate'|'value',value:number|null)=>update({scenarios:m.scenarios.map((x,j)=>j===i?{...x,[key]:value}:x)});return <tr key={s.name}><th>{s.name}</th>{(['activationRate','downstreamRate',...(m.motion==='Sales-led'?['winRate'] as const:[]),'value'] as const).map(key=><td key={key}><Numeric label={s.name+' '+({activationRate:'activation %',downstreamRate:'downstream %',winRate:'win %',value:'value USD'}[key])} value={s[key]} max={key==='value'?1e9:100} onChange={v=>change(key,v)}/></td>)}<td>{number(r?.incremental??null)}</td><td>{number(r?.outcomes??null)}</td>{m.motion==='Sales-led'&&<td>{money(r?.pipeline??null)}</td>}<td>{money(r?.bookings??null)}</td><td>{money(r?.costPerOutcome??null)}</td></tr>})}</tbody></table></div><details><summary>Show calculation and limitations</summary><p>Extra activated = exposed accounts × (test activation − baseline activation). Extra opportunities / paid accounts = extra activated × downstream conversion. Sales pipeline = extra opportunities × opportunity value. Sales bookings = pipeline × win rate. Self-service bookings = extra paid accounts × first-contract value. Cost per extra outcome = total cash and internal time ÷ positive extra outcomes.</p><p>No positive lift means cost per incremental outcome is unavailable. Negative lift is retained. Acquisition costs outside this test, gross margin, retention, revenue recognition and time to close are excluded. This is not company CAC or ROI. Do not sum overlapping experiments.</p></details></section>
 <section className="panel"><h3>4. Make it measurable before funding</h3><div className="econ-columns"><Numeric label="Measurement window (days)" max={730} value={m.windowDays} onChange={v=>update({windowDays:v??0})}/><Numeric label="Minimum accounts per group (justify with power analysis)" max={1e7} value={m.minimumPerGroup} onChange={v=>update({minimumPerGroup:v})}/></div>{(['measurementSource','successRule','stopRule'] as const).map(key=><label className="econ-field" key={key}>{{measurementSource:'Source, attribution method and account deduplication',successRule:'Success threshold and scale rule',stopRule:'Stop rule and guardrails'}[key]}<textarea value={m[key]} onChange={e=>update({[key]:e.target.value})}/></label>)} <div className="econ-decision"><strong>{result?.cash!=null&&cap!==null&&result.cash>cap?'Rescope — cash estimate exceeds the idea cap':result?.decision??'Fix invalid inputs before saving'}</strong>{result&&result.missing.length>0&&<ul>{result.missing.map(item=><li key={item}>{item}</li>)}</ul>}<p>Funding review is a planning checkpoint, not statistical validation or launch approval. Record observed results in Operations; connecting real data remains a separate step.</p></div>{(invalid||error)&&<p role="alert" className="error">{invalid||error}</p>}<button className="primary" disabled={!canSave||saving||!!invalid||!dirty} onClick={async()=>{setSaving(true);setError('');try{await onSave(m);setDirty(false);}catch(e){setError(e instanceof Error?e.message:'Could not save');}finally{setSaving(false);}}}>{saving?'Saving…':'Save assumptions to study'}</button>{!canSave&&<p className="muted">You can explore locally. Save an editable copy of this study to retain your assumptions.</p>}</section></>;
}
