'use client';
import {useState,type ReactNode} from 'react';
import {scenarioNames,type Economics,calculateEconomics} from '@/lib/gtm/economics';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
const cash=(n:number|null)=>n===null?'Add an estimate':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const levels=['Uh-oh','Meh','Interesting','Worth another round'] as const;
export function PostHogImpact({model,result,metric,cap,dirty}:{model:Economics;result:ReturnType<typeof calculateEconomics>|null;metric:string;cap:number|null;dirty:boolean}){
 const [scenario,setScenario]=useState('Base');
 const current=result?.scenarios.find(s=>s.name===scenario);
 const bookings=current?.bookings??null,total=result?.total??null;
 // A deliberately narrow presentation heuristic, not a campaign-quality score.
 const level=bookings===null||total===null||total<=0?null:bookings<=0?0:bookings<total?1:bookings<2*total?2:3;
 const explanations=['No extra bookings in this scenario. Change the idea or learn cheaply.','Some upside, but less than the modeled cost. Keep the test small.','Enough upside to investigate. Try the smallest version first.','This looks worth testing. Earn another round with real results.'];
 const overCap=result?.cash!=null&&cap!==null&&result.cash>cap;
 return <div className="hog-impact"><div className="hog-impact-top"><span className="badge">{model.illustrative?'Illustrative numbers':'Your assumptions'} · not results{dirty?' · unsaved':''}</span><label className="hog-scenario">What if…<Select value={scenario} onValueChange={setScenario}><SelectTrigger aria-label="Impact scenario"><SelectValue/></SelectTrigger><SelectContent>{scenarioNames.map(name=><SelectItem value={name} key={name}>{name==='Conservative'?'It falls flat':name==='Base'?'It goes to plan':'It goes really well'}</SelectItem>)}</SelectContent></Select></label></div>
 <div className="hog-impact-numbers"><article><span>The cash bit</span><strong>{cash(result?.cash??null)}</strong><small>{cash(total)} including team time</small></article><article><span>{model.motion==='Sales-led'?'Potential extra pipeline':'Potential extra paid accounts'}</span><strong>{model.motion==='Sales-led'?cash(current?.pipeline??null):current?.customers==null?'Add an estimate':new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(current.customers)}</strong><small>{cash(bookings)} expected bookings · {model.windowDays} days</small></article></div>
 <section className="hog-meter"><div className="hog-meter-heading"><div><p className="eyebrow">THE SCREW-O-METER</p><h3>{level===null?'Too early to call.':levels[level]}</h3></div><span>{scenario} scenario</span></div><ol className="hog-meter-scale" aria-label="Scenario readout">{levels.map((label,i)=><li key={label} className={i===level?'selected':''} aria-current={i===level?'step':undefined}><span>{i===level?'▲ ':''}{label}</span></li>)}</ol><p>{level===null?'Add costs and conversion assumptions to see where this lands.':explanations[level]}</p><small>A quick read on the assumptions. Not a result, a profit forecast, or permission to spend.</small>{overCap&&<p className="hog-cap-warning">Over the planned cash cap. Trim the scope before trying it.</p>}{result?.overBudget&&<p className="hog-cap-warning">Also above the cash available for this test.</p>}</section>
 <div className="hog-one-signal"><span>One thing to watch</span><strong>{metric}</strong><p>If people remember the stunt but never try the product, we bought a story. Useful, perhaps—but not the outcome this test is aiming for.</p></div>
 </div>;
}
export function EconomicsDetails({playful,children}:{playful:boolean;children:ReactNode}){return playful?<details className="hog-maths"><summary>Show the maths & edit assumptions <span>Costs, scenarios, and the boring-but-useful bits</span></summary><div className="hog-maths-body"><p className="muted">The meter compares expected first-contract bookings with total test cost: zero or negative → Uh-oh; positive but below cost → Meh; 1–2× cost → Interesting; 2× or more → Worth another round. These are presentation bands, not industry benchmarks. Margin, sales overhead, retention, and uncertainty are excluded. A good reading can still lose money. Pipeline is opportunity value, not revenue.</p>{children}</div></details>:<>{children}</>;}
